name: Android CI
# on push we will trigger our code
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 25
        script: ./gradlew connectedCheck
