name: Android CI
# on push we will trigger our code
on: [push]

jobs:
  build:
    runs-on: macos-latest # the machine type
    steps:
      - uses: actions/checkout@v2 #checkout the code
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Run Espresso Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v1 # install and create the Emulator
        with:
          api-level: 25
          target: default
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedDebugAndroidTest -Pcucumber -Ptags="@e2e" --info # running our test with info to check the results
